version: '3'

services:
  steam-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - STEAM_DOWNLOAD_PATH=/data/downloads
    volumes:
      - steam-downloads:/data/downloads
      - steam-cmd:/app/steamcmd
    restart: unless-stopped

volumes:
  steam-downloads:
    driver: local
  steam-cmd:
    driver: local